version: "3.5"
services:
  postgres:
     image: postgres:14-alpine
     environment:
       POSTGRES_PASSWORD: secret
       POSTGRES_DB: nb_workflows
       POSTGRES_USER: nb_workflows 
     ports:
       - 5432:5432
     networks:
       - nb
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - nb
  fileserver:
    image: nuxion/fileserver
    volumes:
      - ./fileserver.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 4444:4444
    networks:
      - nb
  nb-web:
    image: nuxion/nb_workflows
    command: >
      nb web --apps workflows,history,projects,events,runtimes -A --workers 1 -L
    ports:
      - 127.0.0.1:8000:8000
    environment:
      # NB_SQL: sqlite:///app/db.sqlite
      # NB_ASQL: sqlite+aiosqlite:///app/db.sqlite
      NB_SQL: postgresql://nb_workflows:secret@postgres:5432/nb_workflows
      NB_ASQL: postgresql+asyncpg://nb_workflows:secret@postgres:5432/nb_workflows
      NB_RQ_REDIS_HOST: redis
      NB_RQ_REDIS_PORT: 6379
      NB_RQ_REDIS_DB: 2
      NB_FILESERVER: http://fileserver:4444
      NB_WEB_REDIS: redis://redis:6379/0
      NB_SERVER: true
    networks:
      - nb
  nb-worker:
    image: nuxion/nb_workflows
    command: >
      nb rqworker -w 1 -q control,mch.default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      # NB_SQL: sqlite:///app/db.sqlite
      # NB_ASQL: sqlite+aiosqlite:///app/db.sqlite
      NB_SQL: postgresql://nb_workflows:secret@postgres:5432/nb_workflows
      NB_ASQL: postgresql+asyncpg://nb_workflows:secret@postgres:5432/nb_workflows
      NB_AGENT_TOKEN: changethis
      NB_AGENT_REFRESH_TOKEN: changethis
      NB_RQ_REDIS_HOST: redis
      NB_RQ_REDIS_PORT: 6379
      NB_RQ_REDIS_DB: 2
      NB_FILESERVER: http://fileserver:4444
      NB_WEB_REDIS: redis://redis:6379/0
      NB_SERVER: true
    networks:
      - nb




networks:
  nb: 
