FROM python:3.8-slim

RUN apt-get update -y \
	&& apt-get install -y --no-install-recommends curl make git \
	&& curl -sSL https://install.python-poetry.org | POETRY_HOME=/etc/poetry python3 - \
	&& mkdir /app

VOLUME /app
ENV PATH=$PATH:/etc/poetry/bin
ENV PYTHONPATH=/app
RUN poetry config virtualenvs.in-project true
WORKDIR /app
CMD ["python3"]

