version: 0.2.0
project:
  name: pd-name0
  projectid: WzP49tISi1
  username: user0
  description: test
  repository: null
workflows:
  nb-alias0:
    nb_name: nb-name0
    params:
      TEST: true
      TIMEOUT: 5
    machine: default
    docker_version: latest
    enabled: true
    alias: nb-alias0
    description: null
    wfid: 43ncKBffmqPkjpuonR27LE0u
    timeout: 10800
    notifications_ok: null
    notifications_fail: null
  nb-alias1:
    nb_name: nb-name1
    params:
      TEST: true
      TIMEOUT: 5
    machine: default
    docker_version: latest
    enabled: true
    alias: nb-alias1
    description: null
    wfid: 5prBvMMeSbnFzDVfFxqrOlMD
    timeout: 10800
    notifications_ok: null
    notifications_fail: null
  nb-alias2:
    nb_name: nb-name2
    params:
      TEST: true
      TIMEOUT: 5
    machine: default
    docker_version: latest
    enabled: true
    alias: nb-alias2
    description: null
    wfid: 1FVcQDc_eZj8-ir3rYawetOd
    timeout: 10800
    notifications_ok: null
    notifications_fail: null
pipelines:
  sequences: []
