"""auth_system

Revision ID: 0001
Revises: 0000
Create Date: 2022-02-24 12:38:29.146068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = '0000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nb_auth_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nb_auth_group_name'), 'nb_auth_group', ['name'], unique=True)
    op.create_table('nb_auth_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', postgresql.BYTEA(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nb_auth_user_username'), 'nb_auth_user', ['username'], unique=True)
    op.create_table('nb_auth_user_groups',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['nb_auth_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['nb_auth_user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nb_auth_user_groups')
    op.drop_index(op.f('ix_nb_auth_user_username'), table_name='nb_auth_user')
    op.drop_table('nb_auth_user')
    op.drop_index(op.f('ix_nb_auth_group_name'), table_name='nb_auth_group')
    op.drop_table('nb_auth_group')
    # ### end Alembic commands ###
